# Versão da API usada para criar o Deployment
apiVersion: apps/v1
# Tipo do recurso que está sendo criado
kind: Deployment
# Metadados de identificação do recurso
metadata:
  name: infnet-guia  # Nome do deployment
spec:
  replicas: 4  # Número de réplicas (pods) que serão mantidas rodando
  selector:
    matchLabels:
      app: infnet-guia  # Rótulo usado para identificar quais pods pertencem a esse deployment
  template:
    metadata:
      labels:
        app: infnet-guia  # Rótulo aplicado aos pods criados
    spec:
      containers:
      - name: infnet-guia  # Nome do container dentro do pod
        image: jessefi/infnet-guia:latest  # Imagem do container a ser usada (com a tag latest)
        ports:
          - containerPort: 3000  # Porta exposta pelo container
        # Verificação de liveness: checa se o app ainda está rodando
        livenessProbe:
          httpGet:
            path: /  # Caminho a ser acessado na verificação
            port: 3000  # Porta usada na verificação
          initialDelaySeconds: 10  # Tempo inicial antes de iniciar a verificação
          periodSeconds: 5  # Frequência da verificação
        # Verificação de readiness: checa se o app está pronto para receber tráfego
        readinessProbe:
          httpGet:
            path: /  # Caminho a ser acessado na verificação
            port: 3000  # Porta usada na verificação
          initialDelaySeconds: 5  # Tempo inicial antes de iniciar a verificação