apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3001          # Porta interna do service
      targetPort: 3000    # Porta do container (grafana roda aqui)
      nodePort: 30001     # Porta exposta para navegador